HotelApp/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from registr.views import RegisterFormView
# from registr.views import LoginFormView


urlpatterns = [
    # Examples:
    # url(r'^$', 'HotelApp.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', 'HotelApp.views.home', name='home'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^register/', include('registr.urls')),
    url(r'^news/', include('news.urls', namespace='news')),
    # url(r'^admin/', include(admin.site.urls)),
    # url(r'^register/$', RegisterFormView.as_view()),
    # url(r'^login/$', LoginFormView.as_view()),
    # url(r'^exit/$', LoginFormView.as_view()),
]

news/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('news.views',
    url(r'^$', 'news', name='news'),
    url(r'^(?P<post_id>\d+)/$', 'one_new', name='one_new'),
)

registr/urls.py
from django.conf.urls import url, include
from . import views
from registr.views import RegisterFormView

urlpatterns = [
    # url(r'^$', RegisterFormView.as_view()),
    url(r'^register/$', RegisterFormView.as_view()),
    url(r'^$', 'HotelApp.views.home', name='home'),
]

news/models.py
from django.db import models
from django.contrib import admin
from django.contrib.auth.models import User

class Post(models.Model):
    title = models.CharField(max_length=150)
    body = models.TextField()
    timestamp = models.DateTimeField()
    author = models.ForeignKey(User)


    def __unicode__(self):
        return self.title
        return self.body

HotelApp/views.py
from django.shortcuts import render_to_response
from django.template import RequestContext
from news.views import Post


# можно переписать как в news/views.py
def home(request):
    vars = dict (
            posts=Post.objects.all().order_by('-timestamp')[:10],
                )

    return render_to_response('index.html', vars, context_instance=RequestContext(request))

news/views.py
from django.shortcuts import get_object_or_404, render_to_response
from django.template import RequestContext
from .models import Post


def news(request):
    ''' Show all news '''
    posts = Post.objects.all().order_by('-timestamp')
    return render_to_response('news/news.html', {'posts':posts})

def one_new(request, post_id):
    ''' Show single news'''
    post = get_object_or_404(Post, pk=post_id)


    vars = dict(
        title=post.title,
        body=post.body,
        author=post.author,
        timestamp=post.timestamp,
        )

    return render_to_response('news/one_new.html', vars, context_instance=RequestContext(request))

from django.shortcuts import render_to_response
from django.template import RequestContext
#from news.views import Post


# можно переписать как в news/views.py
def home(request):
    vars = dict (
            posts=Post.objects.all().order_by('-timestamp')[:10],
                )

    return render_to_response('index.html', vars, context_instance=RequestContext(request))

registr/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic.edit import FormView
from django.contrib.auth.forms import UserCreationForm

class RegisterFormView(FormView):
    form_class = UserCreationForm

    # Ссылка, на которую будет перенаправляться пользователь в случае успешной регистрации.
    # В данном случае указана ссылка на страницу входа для зарегистрированных пользователей.
    # success_url = '/login/'

    # Шаблон, который будет использоваться при отображении представления.
    template_name = '../registr/template/registr/registr.html'

    def form_valid(self, form):
        # Создаём пользователя, если данные в форму были введены корректно.
        form.save()

        # Вызываем метод базового класса
        return super(RegisterFormView, self).form_valid(form)

# # Опять же, спасибо django за готовую форму аутентификации.
# from django.contrib.auth.forms import AuthenticationForm
#
# # Функция для установки сессионного ключа.
# # По нему django будет определять, выполнил ли вход пользователь.
# from django.contrib.auth import login
#
# class LoginFormView(FormView):
#     form_class = AuthenticationForm
#
#     # Аналогично регистрации, только используем шаблон аутентификации.
#     template_name = "../templates/registr/template/registr/login.html"
#
#     # В случае успеха перенаправим на главную.
#     success_url = "/"
#
#     def form_valid(self, form):
#         # Получаем объект пользователя на основе введённых в форму данных.
#         self.user = form.get_user()
#
#         # Выполняем аутентификацию пользователя.
#         login(self.request, self.user)
#         return super(LoginFormView, self).form_valid(form)
#
# from django.http import HttpResponseRedirect
# from django.views.generic.base import View
# from django.contrib.auth import logout
#
# class LogoutView(View):
#     def get(self, request):
#         # Выполняем выход для пользователя, запросившего данное представление.
#         logout(request)
#
#         # После чего, перенаправляем пользователя на главную страницу.
#         return HttpResponseRedirect("/")
#
#
#
# from django.shortcuts import render_to_response
# from django.template import RequestContext
# from news.views import Post
#
#
# # можно переписать как в news/views.py
# def home(request):
#     vars = dict (
#             posts=Post.objects.all().order_by('-timestamp')[:10],
#                 )
#
#     return render_to_response('index.html', vars, context_instance=RequestContext(request))

news/templates/news/news.html
{% extends 'base.html' %} <!-- подключаем базовый шаблон -->
{% block title %}News{% endblock %}
{% block content %}
    <div id="post">
        {% for post in posts %} <!-- итерация по всем постам -->
            <dl>
              <dd><h3><a href="{% url 'news:one_new' post.id %}">{{ post.title }}</a></h3></dd>
            </dl>
        {{ post.timestamp }} <!-- дата публикации -->
        {{ post.author }} <!-- автор -->
        {{ post.body|truncatewords:80|safe }} <!-- обрезаем посты, вывод по 80 слов -->
        <!-- ссылаемся на полный текст поста -->
        <a href="{% url 'news:one_new' post.id %}">Читать полностью&raquo;</a>
        {% endfor %}
    </div>
{% endblock %}

news/templates/news/one_new.html
{% extends 'base.html' %} <!-- подключаем базовый шаблон -->
<!-- отображать название поста как title страницы-->
{% block title %}{{ title }}{% endblock %}
{% block content %}
Дата: {{ timestamp }}
Автор: {{ author }}
<h1>{{ title }}</h1>
<div>{{ body|safe|escape}}</div> <!-- экранировать HTML-->
<!-- escape переводит HTML-теги, если вы использовали их
    при написании статьи в админке -->
{% endblock %}

templates/base.html
{% load staticfiles %}
<html class="no-js" lang="ru">
<head>
  <meta charset="utf-8">
  <title>MyHotel</title>
  <meta name="HandheldFriendly" content="True" />
  <meta name="MobileOptimized" content="320" />
  <meta content="minimum-scale=1.0, width=device-width, maximum-scale=1.0, user-scalable=no" name="viewport" />
  <meta name="description" content="">
  <link  href="http://fonts.googleapis.com/css?family=Oswald:regular" rel="stylesheet" type="text/css" >
  <link href='http://fonts.googleapis.com/css?family=Junge' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="{% static 'fonts/raphaelicons.css'%}">
  <link rel="stylesheet" href="{% static 'css/main.css'%}">
  <script src="{% static 'js/libs/modernizr-2.5.2.min.js'%}"></script>
  <link href="{% static 'bootstrap3/css/bootstrap.min.css'%}" rel="stylesheet">
</head>
  <header class="clearfix">
      <div class="container">
        <a id="logo" href="index.html">MyHotel</a>
        <ul class="social-icons">
          <button type="button" class="btn btn-info">Вход</button>
          <button type="button" class="btn btn-info">Регистрация</button>
          <button type="button" class="btn btn-info">Забронировать</button>
        </ul>
        <nav class="clearfix">
          <ul role="navigation">
            <li>
              <a href="index.html" class="activePage"><span class="icon">S</span>Главная</a>
            </li>
            <li>
              <a href="portfolio.html"><span class="icon">Û</span>Наши номера</a>
            </li>
            <li>
              <a href="page.html"><span class="icon">E</span>О нас</a>
            </li>
            <li>
              <a href="blog.html"><span class="icon">E</span>Услуги</a>
            </li>
            <li>
              <a href="contact.html"><span class="icon">M</span>Акции и предложения</a>
            </li>
          </ul>
        </nav>
      </div>
  </header>
   <section role="banner">
     <hgroup>
         <h1>ГОСТИНИЦА</h1>
         <h2>МЫ ВАМ РАДЫ</h2>
     </hgroup>
     {% block content %}{% endblock %}
   </section> <!-- // banner ends -->
  <footer role="contentinfo">
      <p>
        <a href="index.html">ГЛАВНАЯ</a> | <a href="portfolio.html">НАШИ НОМЕРА</a> | <a href="page.html">О НАС</a> |  <a href="blog.html">УСЛУГИ</a> | <a href="contact.html">АКЦИИ И ПРЕДЛОЖЕНИЯ</a>
      </p>
  </footer>
</body>
</html>

templates/index.html
{% extends "base.html" %}
{% block title %}Index Page{% endblock %}
{% block content %}
    <div id="post">
        <ul>
        {% for post in posts %}
            <li><a href="{% url 'news:one_new' post.id %}">{{ post.title }}</a></li>
        {% endfor %}
        </ul>
    </div>
{%endblock%}

templates/registr/login.html
<!DOCTYPE html>
<html>
  <head>
    <title>Вход</title>
  </head>
  <body>
    <form action="" method="post">
      {% csrf_token %}
      <!-- as_p для того, чтобы каждый элемент формы был с новой строки -->
      {{ form.as_p }}
      <button type="submit">Вход</button>
    </form>
  </body>
</html>

templates/registr/registr.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <title>Регистрация</title>
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <link rel="stylesheet" type="text/css" href="style.css" />
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
  </head>
  <body>
    <form id="login" action="" method="post">
      {% csrf_token %}
      <!-- as_p для того, чтобы каждый элемент формы был с новой строки -->
        {{  form.as_p }}
        <button type="submit">Зарегистрироваться</button>
    </form>
  </body>
</html>